from core.security.rate_limit import (
    CART_MUTATION_RATE_LIMIT_DEPS,
    FORGET_PASSWORD_RATE_LIMIT_DEPS,
    LOGIN_RATE_LIMIT_DEPS,
    MENU_BOOTSTRAP_RATE_LIMIT_DEPS,
    VALIDATE_CODE_RATE_LIMIT_DEPS,
)
